# Generated by Django 5.0.7 on 2024-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='catalog',
            name='foto',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='price',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
