# Generated by Django 5.0.7 on 2024-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forummessage',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='forummessage',
            name='attached_file',
            field=models.FileField(blank=True, default=None, upload_to='forum_messages'),
        ),
    ]
